# Generated by Django 5.1.6 on 2025-04-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='age',
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
